
CREATE OR REPLACE FUNCTION public.admin_reset_stats()
RETURNS VOID AS $$
BEGIN
  TRUNCATE TABLE transactions RESTART IDENTITY CASCADE;
  TRUNCATE TABLE ad_account_transactions RESTART IDENTITY CASCADE;
  TRUNCATE TABLE notifications RESTART IDENTITY CASCADE;
  TRUNCATE TABLE topup_requests RESTART IDENTITY CASCADE;
  TRUNCATE TABLE account_requests RESTART IDENTITY CASCADE;
  TRUNCATE TABLE invoices RESTART IDENTITY CASCADE;
  TRUNCATE TABLE spend_history RESTART IDENTITY CASCADE;
  TRUNCATE TABLE ad_account_cache RESTART IDENTITY CASCADE;
  
  UPDATE profiles SET wallet_balance = 0;
  UPDATE ad_accounts SET spend_limit = 0, amount_spent = 0, current_spend = 0, user_id = NULL, assigned_at = NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
